import { IconType } from "react-icons";
import { FaJsSquare, FaReact, FaNodeJs, FaPython } from "react-icons/fa";
import {
  SiPostgresql,
  SiFirebase,
  SiMaterialui,
  SiBootstrap,
  SiGit,
  SiExpress,
  SiTypescript,
  SiStyledcomponents,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiNextdotjs,
  SiJest,
} from "react-icons/si";

export const skillIcons: IconType[] = [
  FaNodeJs,
  //   FaJsSquare,
  FaReact,
  SiTypescript,
  FaPython,
  SiPostgresql,
  SiExpress,
  SiBootstrap,
  SiMaterialui,
  SiFirebase,
  SiGit,
  SiTailwindcss,
  SiStyledcomponents,
  SiNextdotjs,
  SiJest,
  SiHtml5,
  SiCss3,
];

export const skillIconNameLookup = [
  "these technologies",
  "Node.js",
  //   "JavaScript",
  "React",
  "TypeScript",
  "Python",
  "PostgreSQL",
  "Express.js",
  "Bootstrap",
  "Material UI",
  "Firebase",
  "Git",
  "Tailwind CSS",
  "Styled Components",
  "Next.js",
  "Jest",
  "HTML5",
  "CSS3",
];
